		<div class="container app">
			<div class="row">
				<div class="col-md-3 menu">
					<ul class="list-group">
                        <li class="list-group-item active" ><a href="/">Tarefas pendentes</a></li>
						<li class="list-group-item "><a href="novatarefa">Nova tarefa</a></li>
						<li class="list-group-item"><a href="todastarefas">Todas tarefas</a></li>
					</ul>
				</div>

				<div class="col-md-9">
					<div class="container pagina">
						<div class="row">
							<div class="col">
								<h4>Tarefas pendentes</h4>
								<hr />
								<?php foreach ($this->view->todastarefas as $tarefa) { ?>
									<div class="row mb-3 d-flex align-items-center tarefa">
										<div id="tarefa_<?= $tarefa['id'] ?>" class="col-sm-9">
											<?= $tarefa['tarefa'] ?> (<?= $tarefa['status'] ?>)
										</div>
										<div class="col-sm-3 mt-2 d-flex justify-content-between">
											<form method="post" id="excluir_tarefa_<?= $tarefa['id'] ?>" action="excluir?origem=index">
												<input type="hidden" value="<?= $tarefa['id'] ?>" name="id">
												<i onclick="excluir(<?= $tarefa['id'] ?>)" class="fas fa-trash-alt fa-lg text-danger"></i>
											</form>
											<?php if ($tarefa['status'] == "Pendente") { ?>
												<i class="fas fa-edit fa-lg text-info" onclick="editar(<?= $tarefa['id'] ?>)"></i>
												<form method="post" id="concluir_tarefa_<?= $tarefa['id'] ?>" action="concluir?origem=index">
													<input type="hidden" value="<?= $tarefa['id'] ?>" name="id">
													<i onclick="concluir(<?= $tarefa['id'] ?>)" class="fas fa-check-square fa-lg text-success"></i>
												</form>
											<?php } ?>
										</div>
									</div>
								<?php } ?>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
