		<?php if (isset($_GET['inclusao'])) {?>
			<div class="bg-success pt-2 text-white d-flex justify-content-center">
				<h5>Tarefa inserida com sucesso! <?=$_GET['inclusao']?></h5>
			</div>
		<?php }?>
		<div class="container app">
			<div class="row">
				<div class="col-md-3 menu">
					<ul class="list-group">
						<li class="list-group-item"><a href="/">Tarefas pendentes</a></li>
						<li class="list-group-item active"><a href="novatarefa">Nova tarefa</a></li>
						<li class="list-group-item"><a href="todastarefas">Todas tarefas</a></li>
					</ul>
				</div>

				<div class="col-md-9">
					<div class="container pagina">
						<div class="row">
							<div class="col">
								<h4>Nova tarefa</h4>
								<hr />

								<form method="post" action="inserir">
									<div class="form-group">
										<label>Descrição da tarefa:</label>
										<input type="text" name="tarefa" required id="tarefa" class="form-control" placeholder="Exemplo: Lavar o carro">
									</div>

									<button onclick="validar()"  class="btn btn-success">Cadastrar</button>
								</form>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
